Web feature test
Jax-Donuts/logger-tool pull request #2
Opened 2023-07-14 04:28 UTC by RYin-28

Created a basic header. 
Did not use sample headers from Mantine because their examples integrated Mantine stylings which made it hard to follow.

2023-07-17 20:07 UTC, drmicrochip97 commented on apps/web/src/App.tsx
> +//import "./App.css";
Remove comments

2023-07-17 20:12 UTC, drmicrochip97 reviewed
Few more changes

2023-07-17 20:12 UTC, drmicrochip97 commented on apps/web/src/common/Top_Header.tsx
> +function Top_Header() {
Change case style to TitleCase
for example
`Top_Header` -> `TopHeader`

2023-07-17 20:12 UTC, drmicrochip97 commented on apps/web/src/main.tsx
> +//import './index.css'
remove comment

2023-07-17 22:17 UTC, drmicrochip97 requested changes

2023-07-17 22:17 UTC, drmicrochip97 commented on apps/web/src/App.tsx
>      </>
You can remove these react fragments `</>`. They're basically divs and aren't needed here.

2023-07-17 22:17 UTC, drmicrochip97 commented on apps/web/src/App.tsx
> +function App() {
I prefer having the export attached to the function name, so for example

```ts
export function App() {
```

You have to modify the import in "main.tsx" like so

```ts
import { App } from "./App.tsx";
```

2023-07-17 22:17 UTC, drmicrochip97 commented on apps/web/src/App.tsx
> -import "./App.css";
Make sure to remove any unneeded files. For example, we are not using App.css so we should be able to just remove it. Same goes for any other files.

2023-07-17 22:17 UTC, drmicrochip97 commented on apps/web/src/App.tsx
> +        <TopHeader />
Can we remove this className? It doesn't look like it's actually used. It also looks like this div isn't used.

2023-07-17 22:17 UTC, drmicrochip97 commented on apps/web/src/common/TopHeader.tsx
> +function TopHeader() {
I would also in this instance 
```ts
export function TopHeader() {
```

and like before modify "App.tsx" to import like so
```ts
import { TopHeader } from "./common/TopHeader";
```

2023-07-17 22:17 UTC, drmicrochip97 commented on apps/web/src/common/TopHeader.tsx
> +      {/* blah */}
nit: Make sure this comment gets removed

2023-07-17 22:17 UTC, drmicrochip97 commented on apps/web/src/common/TopHeader.tsx
> +export default TopHeader;
remove

2023-07-17 22:17 UTC, drmicrochip97 commented on apps/web/src/common/TopHeader.tsx
> +          </Group>
My automatic tool will do this but for right now just remove the white space for " Home ", " Menu ", " Contact Us ", " About ".

2023-07-17 22:17 UTC, drmicrochip97 commented on apps/web/src/common/TopHeader.tsx
> +          </Group>
## Before
```ts
<Button variant = "subtle" size = "md"> Home </Button>
```
## After
```ts
<Button variant = "subtle" size = "md">Home</Button>
```

2023-07-20 23:18 UTC, drmicrochip97 requested changes

2023-07-20 23:18 UTC, drmicrochip97 commented on package.json
> +
remove blank line

2023-07-20 23:18 UTC, drmicrochip97 commented on package.json
> +
fix formatting for this file

2023-07-20 23:18 UTC, drmicrochip97 commented on apps/web/src/libs/menu/menu.tsx
> +// Menu page
Hmm, redundant comment on top you can remove. Same for the other pages

2023-07-20 23:18 UTC, drmicrochip97 commented on apps/web/src/libs/common/top-header/topheader.tsx
> +// Main Header and elements
remove redundant comments.

https://www.youtube.com/watch?v=Bf7vDBBOBUA

2023-07-20 23:18 UTC, drmicrochip97 commented on apps/web/src/libs/common/top-header/topheader.tsx
> +export function TopHeader() {
skewer-case the filename to match the folder `top-header`

2023-07-20 23:18 UTC, drmicrochip97 commented on apps/web/src/libs/common/top-header/topheader.tsx
> +  }
All these functions should be removed in favor of anonymous functions directly in the component since they are really small and simple. For example,

```tsx
<Button variant="subtle" size="md" onClick={() => navigate('/about') }>
   About
</Button>
```

2023-07-20 23:45 UTC, RYin-28 commented on apps/web/src/libs/common/top-header/topheader.tsx
> +export function TopHeader() {
is it fine to keep the function name as `TopHeader`?

2023-07-20 23:52 UTC, drmicrochip97 commented on apps/web/src/libs/common/top-header/topheader.tsx
> +export function TopHeader() {
Yah, components should be TitleCase

2023-07-20 23:57 UTC, drmicrochip97 approved these changes

2023-07-21 00:04 UTC, merged